version: "3"

services:
  localstack:
    image: localstack/localstack
    env_file:
      - .env
    ports:
      - ${EDGE_PORT}:${EDGE_PORT}
    volumes:
      - localstack-volume:${DATA_DIR}
      - "/var/run/docker.sock:/var/run/docker.sock"

  api:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
      - .env
    environment:
      - AWS_ENDPOINT_HOST=http://localstack
    depends_on:
      - localstack
    ports:
      - 8080:8080
      - 8081:8081

volumes:
  localstack-volume: